### ISSUE TITLE
fromSerpent changes 's' to 'bytes'

### ISSUE THREAD

**Issue by tinybike** [ethereumjs/ethereumjs-abi#15]
In the README it has this example:
```
abi.fromSerpent('s')    // [ 'string' ]
```
This is correct.  However when I try it, this returns `['bytes']`.

**Comment by tinybike** [comment]
PR https://github.com/ethereumjs/ethereumjs-abi/pull/16 will fix this once it's merged

**Comment by axic** [comment]
I think this was changed by your PR (https://github.com/ethereumjs/ethereumjs-abi/commit/9817d240ca056d7d8b961366d70012fa5fa103d4).  Which one is correct?
