### ISSUE TITLE
Decoder does not work correctly with fixed-size arrays

### ISSUE THREAD

**Issue by chriseth** [ethereumjs/ethereumjs-abi#29]
The raw output of the function `f` in the following snippet in browser-solidity is correct:
```
contract c {
    uint[2] a;
    function f() returns  (uint[2], uint)  {
        a[0] = 1;
        a[1] = 92;
        return (a, 3);
    }
}
```

But the decoded display shows `[[1,92],92]`.

**Comment by axic** [comment]
I think this was fixed in 0.6.1 - which version is this happening with?
