### ISSUE TITLE
Installation problem with sha3 Debian node v4.6

### ISSUE THREAD

**Issue by diego-G** [ethereumjs/ethereumjs-abi#31]
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sha3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

**Comment by Crypt0-Bear** [comment]
It appears it is a problem with sha3. wonder if installing an older version can fix that

**Comment by axic** [comment]
Thanks for reporting it, @diego-G and @Crypt0-Bear. Since sha3 is a requirement via ethereumjs-util, I'm closing it here.
