### ISSUE TITLE
soliditySHA3 multiple bytes32 encoding issue

### ISSUE THREAD

**Issue by marekkirejczyk** [ethereumjs/ethereumjs-abi#43]
It seems soliditySHA3 does not handle properly case when multiple bytes32 are involved.
Steps to reproduce below:

`abi.soliditySHA3([ "bytes32", "bytes32" ], [ "Volume", "Volume" ]).toString('hex');`
returns:
`8239dae94d559efaf979a8ffdb349ed1d13c6636d28ab641f43ae2bc0c0b985a`

Yet,

```
contract TestTightHash {    
    function coded() constant returns (bytes32) {
        return keccak256(bytes32("Volume"), bytes32("Volume"));
    }
}
```

coded() returns `0x7ab276f38b269dc879fb051ca72ac238c1a03c2db62bbd7a499c1dd822c3e020`

**Comment by marekkirejczyk** [comment]
It works in code downloaded for the master. I think it might be a matter of releasing new version.

**Comment by SeanAvery** [comment]
@marekkirejczyk I am still having an issue with bytes32 packing. How did you resolve this in your code base? Did you have to clone master branch instead of using npm?

**Comment by thisbejim** [comment]
Also confirming this issue, you must install from master for `soliditySHA3` to work properly. I recommend publishing the latest version to npm.

**Comment by D-Nice** [comment]
The issue is with any static bytes type, on the package published on npm. 

It has to do with the solidityPack function, which in the npm package does a return
```js
      return utils.setLengthRight(value, size)
```

while in this repo it seems fixed and actually pushes to the `ret` array instead:
https://github.com/ethereumjs/ethereumjs-abi/blob/master/lib/index.js#L453

Requesting for an update also here
https://github.com/ethereumjs/ethereumjs-abi/issues/54

**Comment by gkucmierz** [comment]
Anyone can resolve that?

**Comment by D-Nice** [comment]
pinging @axic

**Comment by marekkirejczyk** [comment]
We use web3js in beta:
https://web3js.readthedocs.io/en/1.0/web3-eth-abi.html#encodeparameters

**Comment by holgerd77** [comment]
New npm release is out: https://www.npmjs.com/package/ethereumjs-abi

Sorry for the delay, will close now.
