### ISSUE TITLE
How do I go about running index.js inside test folder

### ISSUE THREAD

**Issue by suchitgupta60** [ethereumjs/ethereumjs-abi#48]
Hi, 
I am trying to run the index.js file inside the test folder in order test the application and see how it works. What would be the best way for me run tests. I know a lot of people use truffle or testrpc, beside that how do I go about testing this. 
I have all the dependencies installed. I'm new to this so pardon me if this is off topic.

**Comment by holgerd77** [comment]
Question most-for-sure out of date, will close.
