### ISSUE TITLE
Cutting a new release that includes a `for in` fix

### ISSUE THREAD

**Issue by kzaher** [ethereumjs/ethereumjs-abi#73]
Hi,

I'm having issues for the previous `for in` loop construct. This was fixed in https://github.com/ethereumjs/ethereumjs-abi/commit/3c73e56f8e12cc330174eb38ae6657a9fc1a0fdf

Is it maybe possible to cut a new release with the fixes from the master branch? That would really simplify my life.

**Comment by holgerd77** [comment]
Hi, just published [v0.6.6](https://github.com/ethereumjs/ethereumjs-abi/releases/tag/v0.6.6) of the library, hope that improves the situation.
