### ISSUE TITLE
not installed

### ISSUE THREAD

**Issue by pkgujjar** [ethereumjs/ethereumjs-abi#88]
PS C:\Users\Desktop\dex\pancake-frontend-YT--YT> npm install
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2021-06-22T11_56_47_085Z-debug.log
PS C:\Users\pkgujjar\Desktop\dex\pancake-frontend-YT--YT>

**Comment by seufabio** [comment]
Im facing the same issue, any solutions yet?

**Comment by seufabio** [comment]
@pkgujjar  in case you are still facing it, I solved it adding the following command to my Dockerfile:

RUN apk --no-cache add git

Im using a node alpine image

**Comment by tienvuvietlinkads** [comment]
Your comment save me!

> @pkgujjar in case you are still facing it, I solved it adding the following command to my Dockerfile:
> 
> RUN apk --no-cache add git
> 
> Im using a node alpine image

Your comment save me
It work like a charm

**Comment by caffeinum** [comment]
had the same error, ended up downgrading the package up the dependency tree. not sure what was wrong
