### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by dapp1211** [ethereumjs/ethereumjs-abi#96]
npm WARN tarball tarball data for ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git (null) seems to be corrupted. Trying again.
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-10-07T09_23_55_892Z-debug-0.log

**Comment by RainsChow** [comment]
did u fix this problem?
